name: dt-ca
channels:
- pytorch
dependencies:
- python=3.8
- anaconda
- cudatoolkit=11.
- numpy
- pip
- pip:
  - gym==0.26.2
  - mujoco-py==2.0.2.13
  - numpy
  - torch==2.2
  - transformers==4.5.1
  - wandb==0.9.1
  - scipy
  - configparser
